nohup java -jar  $MONGO_URI  $RIOT_KEY BR &
nohup java -jar  $MONGO_URI  $RIOT_KEY EUNE &
nohup java -jar  $MONGO_URI  $RIOT_KEY EUW &
nohup java -jar  $MONGO_URI  $RIOT_KEY KR &
nohup java -jar  $MONGO_URI  $RIOT_KEY LAN &
nohup java -jar  $MONGO_URI  $RIOT_KEY LAS &
nohup java -jar  $MONGO_URI  $RIOT_KEY NA &
nohup java -jar  $MONGO_URI  $RIOT_KEY OCE &
nohup java -jar  $MONGO_URI  $RIOT_KEY RU &
nohup java -jar  $MONGO_URI  $RIOT_KEY TR &