 java -jar  $MONGO_URI  $RIOT_KEY BR &
 java -jar  $MONGO_URI  $RIOT_KEY EUNE &
 java -jar  $MONGO_URI  $RIOT_KEY EUW &
 java -jar  $MONGO_URI  $RIOT_KEY KR &
 java -jar  $MONGO_URI  $RIOT_KEY LAN &
 java -jar  $MONGO_URI  $RIOT_KEY LAS &
 java -jar  $MONGO_URI  $RIOT_KEY NA &
 java -jar  $MONGO_URI  $RIOT_KEY OCE &
 java -jar  $MONGO_URI  $RIOT_KEY RU &
 java -jar  $MONGO_URI  $RIOT_KEY TR &